"""empty message

Revision ID: 2e3e44f23c2
Revises: 99fc1fd83da
Create Date: 2015-11-13 17:19:47.289599

"""

# revision identifiers, used by Alembic.
revision = '2e3e44f23c2'
down_revision = '99fc1fd83da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###
