"""empty message

Revision ID: 359a75d4ae91
Revises: 37f042adb4b7
Create Date: 2015-11-14 10:30:38.040030

"""

# revision identifiers, used by Alembic.
revision = '359a75d4ae91'
down_revision = '37f042adb4b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('date_favorited', sa.DateTime(), nullable=True))
    op.add_column('entries', sa.Column('favorite', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'favorite')
    op.drop_column('entries', 'date_favorited')
    ### end Alembic commands ###
