"""empty message

Revision ID: 37f042adb4b7
Revises: 2e3e44f23c2
Create Date: 2015-11-13 17:27:28.933618

"""

# revision identifiers, used by Alembic.
revision = '37f042adb4b7'
down_revision = '2e3e44f23c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=12), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    ### end Alembic commands ###
