"""empty message

Revision ID: 99fc1fd83da
Revises: bbba4c4eb15
Create Date: 2015-11-13 16:01:47.158521

"""

# revision identifiers, used by Alembic.
revision = '99fc1fd83da'
down_revision = 'bbba4c4eb15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('username', sa.String(), nullable=True))
    op.create_foreign_key(None, 'entries', 'users', ['username'], ['username'])
    op.drop_column('entries', 'user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.drop_column('entries', 'username')
    ### end Alembic commands ###
